Repository UnBArqDsw2024-1/2024.1_G2_My_Music, pull requests merged in 2024-07, with the labels that each got.

#34 Co-authored-by: Milena Baruc <MilenaBaruc@users.noreply.github.com>
  docs/Assets/Diagrama_Componentes.png
  docs/Modelagem/diagramaComponentes.md
Labels: documentation, enhancement

#41 Diagrama de Estados
  docs/Assets/DiagramadeEstados-Cadastro.png
  docs/Assets/DiagramadeEstados-Login.png
  docs/Assets/DiagramadeEstados-Musica.png
  docs/Modelagem/diagramaEstados.md
Labels: documentation

#48 adicionada ata 2
  docs/Atas/ata_2.md
Labels: documentation

#50 fix: correções ao diagrama de atividades
  docs/Assets/DiagramadeAtividades-Criarplaylist.png
  docs/Modelagem/diagramaAtividades.md
Labels: documentation, fix

#63 Iniciativas extras
  docs/PadroesDeProjeto/IniciativasExtras.md
Labels: documentation, enhancement

#68 Criação do Sprint Planning e Sprint Review
  docs/Sprints/Sprint1/SprintPlanning1.md
  docs/Sprints/Sprint1/SprintReview1.md
Labels: documentation, enhancement

#69 att: Atualizando o mkdocs.yml
  mkdocs.yml
Labels: fix

#65 Adicionando GoFs Criacionais (+ ata da terceira reunião)
  docs/PadroesDeProjeto/GoFsCriacionais.md
  docs/PadroesDeProjeto/IniciativasExtras.md
  mkdocs.yml
Labels: documentation, enhancement

#66 Adicionando GOF Estrutural facade
  docs/Assets/PadroesDeProjeto-Estrutural-Facade.png
  docs/Assets/PadroesDeProjeto-Estrutural-TemplateFacade.png
  docs/PadroesDeProjeto/GoFsEstruturais.md
Labels: documentation

#67 56 gof comportamental command
  docs/Assets/EstruturaCommand.png
  docs/Assets/ModelagemCommand.png
  docs/PadroesDeProjeto/GoFsComportamentais.md
Labels: documentation

#64 Primeira versão do Padrão de projeto Strategy
  docs/Assets/GoFStrategy.png
  docs/PadroesDeProjeto/GoFsExtras.md
Labels: documentation

#70 Feat/participações padroes de projeto
  docs/PadroesDeProjeto/ParticipacoesPadroes.md
Labels: documentation

#72 att: atuailizando código do Factory Method
  docs/PadroesDeProjeto/GoFsCriacionais.md
Labels: documentation, fix
