Repository UnBArqDsw2024-1/2024.1_G2_My_Music, pull requests merged in 2024-04, with the labels that each got.

#23 18 implementar políticas do projeto
  CODE_OF_CONDUCT.md
  docs/PoliticaOrganizacao/PoliticaOrganizacao.md
Labels: documentation

#24 Github Pages
  github-pages/contents/5w2h.md
  github-pages/contents/artefatos.md
  github-pages/contents/brainstorming.md
  github-pages/contents/config.yml
  github-pages/contents/designsprint.md
  github-pages/contents/equipe.md
  github-pages/contents/glossario.md
  github-pages/contents/home.md
  github-pages/contents/lexico.md
  github-pages/contents/mapamental.md
  github-pages/contents/richpicture.md
  github-pages/index.html
  github-pages/static/css/main.css
  github-pages/static/css/styles.css
  github-pages/static/imagens/background.jpg
  github-pages/static/imagens/gamma_icon.ico
  github-pages/static/imagens/photo.png
  github-pages/static/js/bootstrap.bundle.min.js
  github-pages/static/js/bootstrap.bundle.min.js.map
  github-pages/static/js/js-yaml.min.js
  github-pages/static/js/marked.min.js
  github-pages/static/js/scripts.js
Labels: enhancement

#29 Imagens bug fix
  github-pages/contents/artefato5w2h.md
  github-pages/contents/artefatos.md
  github-pages/contents/mapamental.md
  github-pages/contents/richpicture.md
  github-pages/index.html
  github-pages/static/imagens/background.jpg
  github-pages/static/js/scripts.js
Labels: bug
