Repository UnBArqDsw2024-1/2024.1_G2_My_Music, pull requests merged in 2024-08, with the labels that each got.

#87 Ata
  docs/Atas/ata_5.md
  mkdocs.yml
Labels: documentation

#90 Visao implementacao
  docs/ArquiteturaReutilizacao/VisaoDeImplementacao.md
  docs/Assets/VisãodeImplementação.png
Labels: documentation, enhancement

#81 Versão 1 da visão de implantação
  docs/ArquiteturaReutilizacao/VisaoDeImplantacao.md
  docs/Assets/DiagramaImplantação.png
  docs/Assets/DiagramaImplantação2.png
Labels: documentation, enhancement

#92 Prototipo do figma versão 2
  docs/Base/prototipo.md
Labels: enhancement

#82 Adicionando resultado da implementação do command
  docs/Assets/codeCommand.png
  docs/PadroesDeProjeto/GoFsComportamentais.md
Labels: fix

#100 Visão Lógica
  docs/ArquiteturaReutilizacao/visao-de-logica.md
Labels: documentation, enhancement

#108 Miniplayer
  my_music_code/ios/Podfile.lock
  my_music_code/lib/Artist/Components/music_list_tile.dart
  my_music_code/lib/Globals/mini_player.dart
  my_music_code/lib/Globals/navigator_page.dart
  my_music_code/lib/main.dart
  my_music_code/macos/Flutter/GeneratedPluginRegistrant.swift
  my_music_code/pubspec.lock
  my_music_code/windows/flutter/generated_plugin_registrant.cc
  my_music_code/windows/flutter/generated_plugins.cmake
Labels: enhancement, Front_End

#112 Playlist Fix
  my_music_code/lib/Feed/Components/new_music_release.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/Globals/navigator_page.dart
  my_music_code/lib/MyPlaylists/my_playlists_page.dart
  my_music_code/lib/MyPlaylists/new_playlist_page.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
Labels: enhancement, fix, Front_End

#113 Backend Spotify Step 1
  my_music_code/lib/Feed/Components/feed_horizontal_scroll_component.dart
  my_music_code/lib/Feed/Components/feed_music_grid.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/Components/new_music_release.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/SpotifyApi/api_settings.dart
  my_music_code/lib/main.dart
  my_music_code/pubspec.lock
  my_music_code/pubspec.yaml
Labels: bug, fix, Front_End, Back_end

#109 Feat/page search
  my_music_code/assets/eminem.png
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/Search/search_page_terms.dart
  my_music_code/pubspec.yaml
Labels: enhancement, Front_End

#115 Adição de correções e melhorias
  my_music_code/assets/Filter.svg
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/Search/search_page_terms.dart
  my_music_code/pubspec.lock
  my_music_code/pubspec.yaml
Labels: fix, Front_End

#85 Visão processo
  docs/ArquiteturaReutilizacao/visao-de-processo.md
  docs/Assets/AtividadeAdicionarPlaylist.png
  docs/Assets/AtividadeBusca.png
  docs/Assets/AtividadeCompartilhar.png
  docs/Assets/AtividadeRemoverPlaylist.png
Labels: documentation, enhancement

#84 Primeira versão da visão de dados
  docs/ArquiteturaReutilizacao/visaoDados.md
  docs/Assets/visaoDados.png
Labels: documentation, enhancement

#117 Feat/backend/tocar música
  docs/ArquiteturaReutilizacao/VisaoDeImplantacao.md
  docs/ArquiteturaReutilizacao/reutilizacao.md
  docs/ArquiteturaReutilizacao/visao-de-processo.md
  docs/ArquiteturaReutilizacao/visaoDados.md
  docs/Assets/AtividadeAdicionarPlaylist.png
  docs/Assets/AtividadeBusca.png
  docs/Assets/AtividadeCompartilhar.png
  docs/Assets/AtividadeRemoverPlaylist.png
  docs/Assets/reutilizacao1.png
  docs/Assets/reutilizacao2.png
  docs/Assets/visaoDados.png
  my_music_code/assets/Filter.svg
  my_music_code/assets/eminem.png
  my_music_code/lib/Artist/Components/music_list_tile.dart
  my_music_code/lib/Auth/auth_page.dart
  my_music_code/lib/Feed/Components/feed_music_grid.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/Components/new_music_release.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/Globals/navigator_page.dart
  my_music_code/lib/Profile/configuration_page.dart
  my_music_code/lib/Profile/is_added.dart
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/Search/search_page_terms.dart
  my_music_code/pubspec.lock
  my_music_code/pubspec.yaml
Labels: enhancement, Implementation, Back_end

#118 Visao de caso de uso
  docs/ArquiteturaReutilizacao/visao-casos-de-uso.md
  docs/Assets/Diagrama-Casos-uso.png
Labels: documentation, enhancement

#121 103 cadastro e login
  docs/ArquiteturaReutilizacao/visao-de-logica.md
  my_music_code/lib/Auth/login_page.dart
  my_music_code/lib/Auth/signup_page.dart
  my_music_code/lib/Profile/profile_drawer.dart
Labels: enhancement, Back_end

#122 Feat/page search implement
  .gitignore
  my_music_code/lib/Album/album_page.dart
  my_music_code/lib/Auth/auth_page.dart
  my_music_code/lib/Feed/Components/feed_horizontal_scroll_component.dart
  my_music_code/lib/Feed/Components/feed_music_grid.dart
  my_music_code/lib/Feed/Components/feed_profile_app_bar.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/Components/new_music_release.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/Globals/mini_player.dart
  my_music_code/lib/Globals/navigator_page.dart
  my_music_code/lib/Globals/responsive_text.dart
  my_music_code/lib/Globals/spaced_column.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
  my_music_code/lib/Profile/Components/query_result_widget.dart
  my_music_code/lib/Profile/configuration_page.dart
  my_music_code/lib/Profile/friends_page.dart
  my_music_code/lib/Profile/profile_drawer.dart
  my_music_code/lib/Search/Components/filter_item.dart
  my_music_code/lib/Search/Components/query_result_widget.dart
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/Search/search_page_terms.dart
  my_music_code/lib/legal/about_page.dart
  my_music_code/lib/legal/text_section.dart
  my_music_code/lib/universal.dart
  my_music_code/pubspec.lock
  my_music_code/pubspec.yaml
Labels: enhancement, fix, Front_End, Back_end

#123 Save albums
  my_music_code/lib/Album/album_page.dart
  my_music_code/lib/Album/albuns_liked_page.dart
  my_music_code/lib/Album/save_album.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
  my_music_code/lib/universal.dart
  my_music_code/macos/Flutter/GeneratedPluginRegistrant.swift
  my_music_code/pubspec.lock
  my_music_code/pubspec.yaml
Labels: enhancement, fix, Front_End, Back_end

#125 Feat/backend/spotify api 2
  my_music_code/lib/Album/album_page.dart
  my_music_code/lib/Auth/Service/auth_service.dart
  my_music_code/lib/Auth/auth_page.dart
  my_music_code/lib/Auth/login_page.dart
  my_music_code/lib/Auth/signup_page.dart
  my_music_code/lib/Feed/Components/feed_horizontal_scroll_component.dart
  my_music_code/lib/Feed/Components/feed_music_grid.dart
  my_music_code/lib/Feed/Components/feed_profile_app_bar.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Feed/music_page.dart
  my_music_code/lib/Globals/mini_player.dart
  my_music_code/lib/Globals/navigator_page.dart
  my_music_code/lib/Globals/responsive_text.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
  my_music_code/lib/Profile/configuration_page.dart
  my_music_code/lib/Profile/profile_drawer.dart
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/SpotifyApi/get_data.dart
  my_music_code/lib/universal.dart
Labels: enhancement, fix, Front_End, Back_end

#116 Doc arq de software
  docs/ArquiteturaReutilizacao/arquiteturaDeSoftware.md
  docs/ArquiteturaReutilizacao/visaoIntegracao.md
  mkdocs.yml
Labels: documentation, enhancement

#120 Entrega
  docs/ArquiteturaReutilizacao/VisaoDeImplantacao.md
  docs/ArquiteturaReutilizacao/VisaoDeImplementacao.md
  docs/ArquiteturaReutilizacao/reutilizacao.md
  docs/ArquiteturaReutilizacao/visao-casos-de-uso.md
  docs/ArquiteturaReutilizacao/visaoDados.md
  docs/Assets/LogoMyMusic.png
  docs/_sidebar.md
  docs/index.md
  mkdocs.yml
  my_music_code/ios/Podfile.lock
Labels: documentation

#124 fix(): Correção dos diagramas
  docs/ArquiteturaReutilizacao/visao-de-processo.md
  docs/Assets/AtivAdicionarPlaylist.png
  docs/Assets/AtivBuscarMusica.jpeg
  docs/Assets/AtivCompartilhar.png
  docs/Assets/AtivRemoverPlaylist.png
  docs/Assets/DiagAtvAdicionarPlaylist.png
  docs/Assets/DiagAtvBuscarMusica.png
  docs/Assets/DiagAtvCompartilharMusica.jpeg
  docs/Assets/DiagAtvRemoverPlaylist.png
Labels: enhancement

#130 Modularizar playlists page
  my_music_code/lib/Album/album_widgets.dart
  my_music_code/lib/MyPlaylists/playlist_widgets.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
  my_music_code/pubspec.lock
Labels: fix, Back_end

#131 Logo update Ver 1
  my_music_code/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  my_music_code/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  my_music_code/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  my_music_code/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  my_music_code/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
Labels: enhancement

#134 Correção de navegação
  my_music_code/lib/Album/album_page.dart
  my_music_code/lib/Artist/artist_page.dart
  my_music_code/lib/Auth/auth_page.dart
  my_music_code/lib/Feed/Components/music_playlist_feed_component.dart
  my_music_code/lib/Feed/Components/new_music_release.dart
  my_music_code/lib/Feed/feed_page.dart
  my_music_code/lib/Globals/mini_player.dart
  my_music_code/lib/Music/Components/modal_music.dart
  my_music_code/lib/Music/Components/music_options_modal.dart
  my_music_code/lib/Music/music_page.dart
  my_music_code/lib/MyPlaylists/new_playlist_page.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
  my_music_code/lib/Profile/Backend/update_profile.dart
  my_music_code/lib/Search/search_page.dart
  my_music_code/lib/Search/search_page_terms.dart
  my_music_code/lib/navigator_page.dart
  my_music_code/lib/universal.dart
Labels: fix, Back_end

#135 Liked songs page
  my_music_code/analysis_options.yaml
  my_music_code/lib/Album/album_page.dart
  my_music_code/lib/Album/albuns_liked_page.dart
  my_music_code/lib/Auth/auth_page.dart
  my_music_code/lib/Models/music_model.dart
  my_music_code/lib/Music/list_liked_music_widgets.dart
  my_music_code/lib/Music/music_page.dart
  my_music_code/lib/Music/save_music.dart
  my_music_code/lib/MyPlaylists/user_page_of_playlists.dart
Labels: enhancement, fix, Front_End, Back_end

#136 Sprint 2
  docs/ArquiteturaReutilizacao/participacoesArqReutilizacao.md
  docs/Sprints/Sprint2/SprintPlanning2.md
  docs/Sprints/Sprint2/SprintReview2.md
Labels: documentation
